### ISSUE TITLE
swarm - connection refused

### ISSUE THREAD

**Issue by FabienDaniel** [patchy631/ai-engineering-hub#1]
Hello,

I just tried to run the `demo.ipynb` notebook but I have an issue related to **swarm**. 
While executing the code, I got a `ConnectError: [Errno 111] Connection refused` message.

Do I need to provide an OpenAI API token to be able to use swarn ?

**Comment by patchy631** [comment]
Did you start a model server: https://ollama.com/

It's fairly easy to setup, check the guide on ollama.com

Let me know if the issue still persists.
